### ISSUE TITLE
Microsoft.Maker.Serial available() and read() stops providing data back from Arduino

### ISSUE THREAD

**Issue by edwyn** [ms-iot/serial-wiring#11]
Hi,

**General Introduction**
I am using the rapsberry pi 2 and connected the arduino mega 2560 via USB
Plus i am also using a chinese arduino clone with an ftdi chipset.

I am using the SerialSample from the windows site but have changed it to use the following code
and this part works greate.

`usb = new UsbSerial("VID_2341", "PID_0010");   //Arduino available in Lantern`
`usb.ConnectionEstablished += OnConnectionEstablished;`
 `usb.begin(250000, SerialConfig.SERIAL_8N1);`

when connection is being made the arduino will send a bunch of data ~816 bytes back to the raspberry pi 2 with all kind of diagnostic information.

Case:arduino mega 2560
to read-out the data i've created the following code:

`bool isRead=true;`
`while (isRead)`
`{`
`// usb.@lock();`
`usbavt = usb.available();`
`t = (byte)readBuf;`
`_ByteList.Add(t);`
`if(usbavt == 0)`
`{`
`//no more data to read`
`isRead = false;`
`}`
`}`

not all data is read that i expect, but its just diagnostic so .. i am ok with it.. for now..

via the serial connection i send out a command to the arduino, expecting some more diagnostic data again.

`var buffer = Encoding.ASCII.GetBytes("M114\n").ToArray();`
`usbcheck= usb.write(buffer);`
`usb.flush();`

the first time reading out the data i am still getting some data..
after a second time.. the usb.read() data is only returning 65535.

and usb.available() is returning 0 

the arduino is receiving and sending data, the leds flash when i flush().
and the arduino reacts to the send data from C#, I have a stepper motor that i can move 

is this a known issue, is this an issue at all :)

**Expected behavior**
bufferdata from arduino can always be read.

*

**Comment by zfields** [comment]
How are you writing data to the Arduino? Are you manipulating it directly through the UsbSerial object? If you are using remote-wiring, then you are competing with the read thread used by the firmata layer.

**Comment by zfields** [comment]
I just merged a pull-request that may address this concern. Thank you for reporting.

**Comment by edwyn** [comment]
hi zfields how to test your merge :)

**Comment by zfields** [comment]
You should be able to compile the library from source code to see the changes immediately, or you can wait until the team responsible for this project publishes a new NuGet package.

**Comment by IoTGirl** [comment]
Closing based on pull request and answer given
