### ISSUE TITLE
SerialDevice::FromIdAsync returned null on USB 2.0, while non-null on USB3.0 on the same X64 computer

### ISSUE THREAD

**Issue by jimaobian** [ms-iot/serial-wiring#17]
Hi, when trying to use remote-wiring on [lattepanda](http://www.lattepanda.com)(windows 10 maker board), this odd problem happens.

Actually there is an onboard Leonardo chips connect to USB 2.0. However it cannot work. So I try to connect external Board to test it. This is the result.

noted: DeviceCapability is enabled.

Leonardo Board --> USB 3.0    remote-wiring working;  Arduino upload working;
Leonardo Board --> USB 2.0    remote-wiring not working;  Arduino upload working;

This is the [source code](https://github.com/DFRobot/DFRobotWindowsIoTTempelate)

**Comment by zfields** [comment]
I don't have the hardware you are working with to diagnose and test. I'll leave this open, in case we can reproduce this on different hardware. Thanks for reporting!

**Comment by wsywsya119** [comment]
Same problem as yours.
Anyone have idea?

**Comment by zfields** [comment]
Do you have the latest firmware for the Latte Panda?

**Comment by saraclay** [comment]
Closing this out as this has likely been fixed by new releases since. Feel free to file an issue on ms-iot/content as we are more active there.
