### ISSUE TITLE
Windows 10 IoT, can't add references to projects

### ISSUE THREAD

**Issue by TonyScarpelli** [ms-iot/serial-wiring#18]
I am using Visual Studio 2015, version 14.0.25123.00 Update 2, and Windows 10.
I'm going through the project on this page:
https://developer.microsoft.com/en-us/windows/iot/win10/WRA.htm#new-project
Develop with Windows Remote Arduino
I add the three projects to the solution:
Microsoft.Maker.Firmata.vcxproj
Microsoft.Maker.RemoteWiring.vcxproj
Microsoft.Maker.Serial.vcxproj
But when I try to add a reference to the projects, they don't show up in the Reference Manager under Projects/Solution
I can Browse to them, and add them to the Browse/Recent list, but then they don't get added as a reference, I get an error message saying they can't be added.
Any ideas why this isn't working?
Thanks

**Comment by IoTGirl** [comment]
Hi Tony,
Please retry with the latest tools. From your statement above it sounds like something did not register properly.
Sincerely,
IoTGirl
