### ISSUE TITLE
Embedded UART from RaspberryPi running Windows 10 IoT Core not working

### ISSUE THREAD

**Issue by Ellerbach** [ms-iot/serial-wiring#19]
So looks like there is an issue with the embedded UART from the RPI on Windows 10 IoT Core. When I pass the DeviceInformation from the embedded UART (see code below) it's not working. I never get to the ConnectionEstablished. If I plug a Serial USB FTDI and pass with the same code the DeviceInformation, it does work. Is it a problem related to the embedded Serial port?

```
        string aqs = SerialDevice.GetDeviceSelector();
        var dis = await DeviceInformation.FindAllAsync(aqs);
        for (int i = 0; i < dis.Count; i++)
        {
            Debug.WriteLine(string.Format("Serial device found: {0}", dis[i].Id));
            if (dis[i].Id.IndexOf("UART0") != -1)
            {
                connection = new UsbSerial(dis[i]);
                arduino = new RemoteDevice(connection);
                connection.ConnectionEstablished += Connection_ConnectionEstablished;
                connection.begin(115200, SerialConfig.SERIAL_8N1);
            }
        }
```

**Comment by zfields** [comment]
There is a bit you need to set on the USB config  #13. I'm getting back into this project and I'll put a fix in. Thanks for reporting!

**Comment by IoTGirl** [comment]
Closing as stale
