### ISSUE TITLE
namespace "Microsoft::Maker" has no member "Serial"	 ??? 

### ISSUE THREAD

**Issue by rumred** [ms-iot/serial-wiring#5]
I have 237 errors and all of them have something to do with Serial project that I included ..

**Comment by zfields** [comment]
Can you provide more detail? Where did your code come from?

**Comment by zfields** [comment]
You likely need to add a reference to the serial-wiring project in your code.

**Comment by zfields** [comment]
You should try installing remote-wiring using the NuGet package. I'm going to mark this as resolved until I hear back from you. Thanks for reporting your issue!
